#!/bin/bash

CURRENT_BRANCH="$(git symbolic-ref --short HEAD 2>/dev/null)"

PROTECTED_BRANCH_REGEX='(release\/dev|release\/stag|release\/prod)'
BRANCH_NAME_REGEX='((feat|fix|docs|style|refactor|perf|test|chore|revert|wip|build|ci)\/)((([a-z]{3,}-?)){1,3}#[0-9]{5})'

if [[ "$CURRENT_BRANCH" =~ $PROTECTED_BRANCH_REGEX ]]
then
    echo "You can't commit on protected branches..."
    exit 1
fi


if [[ "$CURRENT_BRANCH" = "main" ]]
then
    npx lint-staged
    exit 0
elif [[ ! "$CURRENT_BRANCH" =~ $BRANCH_NAME_REGEX ]]
then
    echo "Invalid branch name format.... ( FORMAT: {type}/{module}#{proofhub-id} )"
    echo "Valid branch name examples: feat/auth#39281, fix/user-crud#89462, refactor/post-create-operation#97281"
    exit 1
fi

npx lint-staged
exit 0
